### ISSUE TITLE
Move navbar outside motion div to exclude from transition

### ISSUE THREAD

**Issue by grikomsn** [indraarsy/landing-page#1]
Hi there,

https://github.com/indraarsy/landing-page/blob/f4924dffab4cea3121ec69664f6692ee343ebd0c/pages/_app.js#L24-L47

Noticed that the navbar is inside the motion div which makes the page transition include the navbar. My suggstion is to move the navbar outside the motion div and use `<AnimatePresence exitBeforeEnter />` to include an exit transition. Here's my implementation if you need any references: https://github.com/grikomsn/griko.id/blob/b3fc857d51af35d786982c02e72a341cd012de1d/packages/v7/pages/_app.tsx#L129-L142

So roughly your fix would be something like this:

```js
<>
  <Nav />
  <AnimatePresence exitBeforeEnter>
    <motion.div>
      <Component {...pageProps} />
    </motion.div>
  </AnimatePresence>
</>

```

Hope this helps! 👋

**Comment by indraarsy** [comment]
Thanks alot!, fixed with the new commit
